version: '2'

services:
  app:
    image: 'drone-controller:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    expose:
      - 8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/drone_controller
      - SPRING_DATASOURCE_USERNAME=postgres_user
      - SPRING_DATASOURCE_PASSWORD=postgres_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=live
    volumes:
      - ~/Documents:/user/local/Documents
    network_mode: host


  db:
    build:
      context: .
      dockerfile: DBDockerfile
    volumes:
      - .:/docker-entrypoint-initdb.d/
    container_name: db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    ports:
      - "5432:5432"
    network_mode: host


#  docker rm -f $(docker ps -a -q)
