server:
  port: 8081
  error:
    include-message: always
#    include-binding-errors: always
#    include-stacktrace: ON_PARAM
#    include-exception: true

spring:
#  datasource:
#    username: postgres-user
  #  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: user
#    password: password
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect